image: maven:3.8.5-openjdk-17

variables:
  ARTIFACTORY_URL: https://idirotest.jfrog.io/artifactory
  ARTIFACTORY_REPO: spring-petclinic-libs-release

stages:
  - publish
  - compile
  - test
  - package


publish:
  stage: publish
  script:
    - mvn deploy -DskipTests -Drepo.user=$ARTIFACTORY_USER -Drepo.password=$ARTIFACTORY_PASSWORD

compile:
  stage: compile
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn package
