image: maven:3.8.5-openjdk-17

variables:
  ARTIFACTORY_URL:  https://idirotest.jfrog.io
  ARTIFACTORY_REPO_RELEASE: spring-petclinic-libs-release
  ARTIFACTORY_REPO_SNAPSHOT: spring-petclinic-libs-snapshot
  JFROG_BUILD_STATUS: "PASS"

stages:
  - build

jfrog-ci-integration:
  stage: build
  image: adoptopenjdk:11-jdk-hotspot
  script:
    - apt-get update && apt-get install -y curl
    - curl -fL https://getcli.jfrog.io | sh
    - export PATH=$PATH:`pwd`
    - export MVN_PATH=`which mvn` && export M2_HOME=`readlink -f $MVN_PATH | xargs dirname | xargs dirname`
    - export BUILD_NAME=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.artifactId}-${project.version}' --non-recursive exec:exec)
    - export VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
    - jfrog c add --user=${ARTIFACTORY_USER} --password=${ARTIFACTORY_PASSWORD} --url=${ARTIFACTORY_URL} --interactive=false
    - jfrog rt mvn-config --server-id-resolve=${ARTIFACTORY_URL} --repo-resolve-releases=${ARTIFACTORY_REPO_RELEASE} --repo-resolve-snapshots=${ARTIFACTORY_REPO_SNAPSHOT}
    - jfrog rt mvn clean install --build-name=${BUILD_NAME} --build-number=${VERSION} || export JFROG_BUILD_STATUS="FAIL"
    - jfrog rt bce ${BUILD_NAME} ${VERSION}
    - jfrog rt bag ${BUILD_NAME} ${VERSION}
    - jfrog rt bp ${BUILD_NAME} ${VERSION}
    - jfrog rt bs ${BUILD_NAME} ${VERSION}
