image: maven:3.8.5-openjdk-17

variables:
  MAVEN_SETTINGS_PATH: ".m2/settings.xml"

stages:
  - publish
  - compile
  - test
  - package


publish:
  stage: publish
  script:
    - mvn deploy -DskipTests

compile:
  stage: compile
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn package


