image: maven:3.8.5-openjdk-17

variables:
  ARTIFACTORY_URL: https://idirotest.jfrog.io
  ARTIFACTORY_REPO: spring-petclinic-libs-release
  MAVEN_SETTINGS_PATH: ".m2/settings.xml"

stages:
  - publish
  - compile
  - test
  - package


publish:
  stage: publish
  script:
    - ./mvnw deploy -DskipTests -s ./.m2/settings.xml

compile:
  stage: compile
  script:
    - ./mvnw compile

test:
  stage: test
  script:
    - ./mvnw test

package:
  stage: package
  script:
    - ./mvnw package


