image: maven:3.8.3-openjdk-17

variables:
  ARTIFACTORY_URL:  https://idirotest.jfrog.io
  ARTIFACTORY_REPO_RELEASE: spring-petclinic-libs-release
  ARTIFACTORY_REPO_SNAPSHOT: spring-petclinic-libs-snapshot
  JF_URL: ${ARTIFACTORY_URL}
  JF_USER: ${ARTIFACTORY_USER}
  JF_PASSWORD: ${ARTIFACTORY_PASSWORD}
  JFROG_BUILD_STATUS: "PASS"

include:
  - remote: "https://releases.jfrog.io/artifactory/jfrog-cli/gitlab/v2/.setup-jfrog-unix.yml"

stages:
  - build

before_script:
  - !reference [ .setup_jfrog, script ]
  - export BUILD_NAME=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.artifactId}-${project.version}' --non-recursive exec:exec)
  - export VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
  - jf mvn-config --server-id-resolve=${ARTIFACTORY_URL} --repo-resolve-releases=${ARTIFACTORY_REPO_RELEASE} --repo-resolve-snapshots=${ARTIFACTORY_REPO_SNAPSHOT}

jfrog-ci-integration:
  stage: build
  script:
    - !reference [ .setup_jfrog, script ]
    - jf mvn clean install --build-name=${BUILD_NAME} --build-number=${VERSION} || export JFROG_BUILD_STATUS="FAIL"
    - jf rt bce ${BUILD_NAME} ${VERSION}
    - jf rt bag ${BUILD_NAME} ${VERSION}
    - jf rt bp ${BUILD_NAME} ${VERSION}
#    - jf bs ${BUILD_NAME} ${VERSION}
  after_script:
    - !reference [.cleanup_jfrog, script]
