image: maven:3.8.5-openjdk-17

variables:
  ARTIFACTORY_URL:  https://idirotest.jfrog.io
  ARTIFACTORY_REPO_RELEASE: spring-petclinic-libs-release
  ARTIFACTORY_REPO_SNAPSHOT: spring-petclinic-libs-snapshot
  MAVEN_SETTINGS_PATH: ".m2/settings.xml"

stages:
  - build

jfrog-ci-integration:
  stage: build
  image: adoptopenjdk:11-jdk-hotspot
  script:
    - apt-get update && apt-get install -y curl
    - curl -fL https://getcli.jfrog.io | sh
    - export PATH=$PATH:`pwd`
    - export MVN_PATH=`which mvn` && export M2_HOME=`readlink -f $MVN_PATH | xargs dirname | xargs dirname`
    - jfrog c add --user=${ARTIFACTORY_USER} --password=${ARTIFACTORY_PASSWORD} --url=${ARTIFACTORY_URL} --interactive=false
    - jfrog rt mvn-config --server-id-resolve=${ARTIFACTORY_URL} --repo-resolve-releases=${ARTIFACTORY_REPO} --repo-resolve-snapshots=${ARTIFACTORY_REPO_SNAPSHOT}
    - jfrog rt mvn clean install || export JFROG_BUILD_STATUS="FAIL"
    - jfrog rt bce
    - jfrog rt bag
    - jfrog rt bp
    - jfrog rt bs
  only:
    - master
