name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          cache: maven
          distribution: 'adopt'

      - name: Build docker image
        run: docker build -t ${{ vars.ARTIFACTORY_URL }}/${{ vars.ARTIFACTORY_DOCKER_REPO }}/sping-petsclinic:${{ github.ref_name }} .

      - name: Build with Jfrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_USER: ${{ vars.ARTIFACTORY_USER }}
          JF_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Run Jfrog CLI
        run: |
          jf --version
          jf rt bce
          jf rt bag
          jf rt bp
          jf rt dp ${{ vars.ARTIFACTORY_URL }}/${{ vars.ARTIFACTORY_DOCKER_REPO }}/sping-petsclinic:${{ github.ref_name }} my-docker-repo-in-artifactory
