name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t ${{ vars.ARTIFACTORY_DOCKER_REPO }}/spring-petsclinic:${{ github.ref }} .

      - name: Tag docker image
        run: docker tag ${{ vars.ARTIFACTORY_DOCKER_REPO }}/spring-petsclinic:${{ github.ref }} idirotest.jfrog.io/${{ vars.ARTIFACTORY_DOCKER_REPO }}/spring-petclinic:${{ github.ref }}

      - name: Build with Jfrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Run Jfrog CLI
        run: |
          jf rt bce
          jf rt bag
          jf docker push idirotest.jfrog.io/${{ vars.ARTIFACTORY_DOCKER_REPO }}/spring-petclinic:${{ github.ref }}
          jf rt bp
          jf bs --fail=false
