name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          cache: maven
          distribution: 'adopt'

      - name: Build with Jfrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JFROG_CLI_OFFER_CONFIG: false
          JF_URL: ${{ environment.ARTIFACTORY_URL }}
          JF_USER: ${{ environment.ARTIFACTORY_USER }}
          JF_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Run Jfrog CLI
        run: |
          jf --version
          jf rt ping
          jf rt bce
          jf rt bag
          jf rt bp

