name: JFrog CLI CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          cache: maven
          distribution: 'adopt'
      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          export PATH=$PATH:`pwd`
      - name: Configure Artifactory
        run: |
          jfrog rt config --url ${{ secrets.ARTIFACTORY_URL }} --user ${{ secrets.ARTIFACTORY_USER }} --password ${{ secrets.ARTIFACTORY_PASSWORD }} --interactive=false
      - name: Publish to Artifactory
        run: |
          jfrog rt u "target/*.jar" ${{ secrets.ARTIFACTORY_REPO }}
