name: JFrog CLI CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          cache: maven
          distribution: 'adopt'

      - name: Build with Jfrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JFROG_CLI_OFFER_CONFIG: false
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
          JF_USER: ${{ secrets.ARTIFACTORY_URL }}
          JF_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Configure Artifactory
        run: |
          jf rt config --url ${{ secrets.ARTIFACTORY_URL }} --user ${{ secrets.ARTIFACTORY_USER }} --password ${{ secrets.ARTIFACTORY_PASSWORD }} --interactive=false
      - name: Publish to Artifactory
        run: |
          jf rt u "target/*.jar" ${{ secrets.ARTIFACTORY_REPO }}
