name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  MAVEN_SETTINGS_PATH: ".m2/settings.xml"
  ARTIFACTORY_URL: https://idirotest.jfrog.io

jobs:
  publish:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          cache: maven
          distribution: 'adopt'
      - name: Check environment variables
        run: printenv | grep ARTIFACTORY
      - name: Publish to Artifactory
        run: ./mvnw deploy -DskipTests -s ${{ env.MAVEN_SETTINGS_PATH }}


